server:
  port: 8070

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/books/**
          - id: library-service
            uri: lb://library-service
            predicates:
              - Path=/libraries/**
            filters:
              - name: CircuitBreaker
                args:
                  id: library
                  name: backendB
                  fallbackUri: forward:/library-fallback
          - id: test-service
            uri: https://www.google.com/
            predicates:
              - Path=/redirect/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    backendB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 15
      waitDurationInOpenState: 30s
      failureRateThreshold: 40
      eventConsumerBufferSize: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true